//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TerenWebApi {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Sql {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Sql() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TerenWebApi.Sql", typeof(Sql).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INSERT INTO nteren_error_log
        ///(tl_data, 
        /// tl_dodatkoweInformacje, 
        /// tl_stacktrace, 
        /// tl_tt_id
        ///)
        ///VALUES
        ///(GETDATE(), 
        /// @AdditionalInfo, 
        /// @StackTrace, 
        /// @UserId
        ///);.
        /// </summary>
        public static string AddErrorLog {
            get {
                return ResourceManager.GetString("AddErrorLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INSERT INTO [dm_data_gci].[dbo].nteren_jwt
        ///(tj_tt_id, 
        /// tj_token, 
        /// tj_data_od, 
        /// tj_data_do
        ///)
        ///VALUES
        ///(@UserId, 
        /// @Token, 
        /// GETDATE(), 
        /// @ExpirationDate
        ///);.
        /// </summary>
        public static string AddJwt {
            get {
                return ResourceManager.GetString("AddJwt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT tt_id AS Id, 
        ///       tt_imie AS Name, 
        ///       tt_nazwisko AS Surname, 
        ///       tt_login AS Login
        ///FROM nteren_terenowi
        ///     JOIN nteren_terenowy_urzadzenie ON ttu_tt_id = tt_id
        ///                                        AND ttu_data_do &gt; GETDATE()
        ///     JOIN nteren_urzadzenia ON tu_id = ttu_tu_id
        ///                               AND tu_imei = @Imei
        ///                               AND tu_sn = @Sn
        ///                               AND tu_czy_aktywny = 1
        ///WHERE tt_login = @Login
        ///      AND tt_pin = @Pin
        /// [rest of string was truncated]&quot;;.
        /// </summary>
        public static string GetUserByIndentity {
            get {
                return ResourceManager.GetString("GetUserByIndentity", resourceCulture);
            }
        }
    }
}
